### ISSUE TITLE
Fee

### ISSUE THREAD

**Issue by Alehow** [Marabun/CryptusBlock#20]

**Comment by Alehow** [comment]
[Uploading Снимок экрана_2019-02-26_12-42-55.png...]

**Comment by Alehow** [comment]
![Снимок экрана_2019-02-26_12-42-55.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a78339ad9a61700135eaf3e/125516c66e82c728ace21e0d4658552afe325b19535961f37e1d4179999c969399d413f6c055dc7aef13224c5f5d53ae47375e46e1fd8b36a3b32e6c981c49b28b380c30d43703a9eb861aea06b8248e4c83e7b58f4cc4b9382db1898a196c0c190acbae0361ffc412820db459eb5f57a6193766e377377b409d1c71286c6f34e6.png)

**Comment by Marabun** [comment]
Если брать меньшую общую  комсу, это будем просто большая из всех наименьших из последних 10 блоков. Например, комса начала расти от блока к блоку, естественно, что большая из наименьших будет в последнем блоке. И это нам мало чего  дает. И если в след. блоке комса еще вырастет, то транза, на основе такого метода, не попадет в блок. Давай как ты сказл, будем брать от 10%
