### ISSUE TITLE
Диалог с хешем транзакции

### ISSUE THREAD

**Issue by Marabun** [Marabun/CryptusBlock#4]
Сокращать хеш транзакции до шести знаков и форматировать текст курсив, жирный:

Transaction ID _86a431..._ get **3** confirmations

![Screenshot_20190129-124900_Plus.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd7917752a6455f17f29d5b3178f4e6e124d435cec03070511afbd9b21b4b36f748f090cefd5685c72973414acbcd31ab757b825dd1d97aaaec81d9ebc6278bec1da0d2c14171981f55c30a4914ccd51f04de24b50ac017b.jpg)

**Comment by Alehow** [comment]
Мне на каком-то интуитивном уровне кажется что лучше оставлять последние 6 символов, а не первые 6. Или лучше как ты сказал?

**Comment by Marabun** [comment]
Это важно для адресов транзакций видеть последние символы, для хеша транзакции, тем более в этом случае, когда мы же сами его и даём, достаточно видеть начало .
