### ISSUE TITLE
Диалог Play new block

### ISSUE THREAD

**Issue by Marabun** [Marabun/CryptusBlock#6]
Добавить номер
![Screenshot_20190129-141445_Plus.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd7917752a6455f77a24d1b6178f4e6e124d435cec03070511afbd9b21b4b36f748f090cefd5685c72973414acbcd31ab757b825dd1d97aaaec81d9ebc6278bec1da0d2c14171981f55c30a4914cce5cf74ce44a55a1017b.jpg)

**Comment by Alehow** [comment]
Кстати, уже сделал, чем самого напрягало что не пишет)
